### ISSUE TITLE
A question about ERM

### ISSUE THREAD

**Issue by winerholiday** [JoSangYoung/Official-POEM#1]
Hello, I want to say thank you for your great work first!

I wonder  how can  I   implement the ERM algorithm（not POEM which is named  ERM in POEM/domainbed/algorithms/algorithms.py）without SWAD.  

IF I ONLY change the ERM class(POEM/domainbed/algorithms/algorithms.py) into ERM class [DomainBed] and run your code,is this correct? And are _bool_angle True --bool_task_  necessary  in this case?

Thanks!

**Comment by winerholiday** [comment]
And if i want to choose SWAD ,why not args --bool_swad?
your code is '--swad True' rather than '--bool_swad True'

**Comment by JoSangYoung** [comment]
Hi! I appreciate you are interested in POEM and contact me.

If you want to learn only ERM(without L_s, L_d, and SWAD), you can turn off
3 args which are --bool_angle, --bool_task, and --swad.

For example, you can try command without any arguments above because their
default values are set as "False".

I did not check there is --bool_swad argument. Perheps, That might be trace
of debugging.

Thank you for your attention.

2023년 3월 4일 (토) 오전 1:39, winerholiday ***@***.***>님이 작성:

**Comment by winerholiday** [comment]
Thank you for your kind reply！

However, I still want to check the use of '--swad' and '--bool_swad‘

The arg '--swad' is in POEM/config.yaml(default swad: LossValley) 
```
# Default update config
# Config order: hparams_registry -> config.yaml -> CLI
scheduler: const

swad: LossValley
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 1.3
test_batchsize: 128
indomain_test: False  # use indomain test split or not
```
while the '--bool_swad' is in POEM/train_all.py(default=False, help="bool swad to networks" ). 
`parser.add_argument("--bool_swad", type=bool, default=False, help="bool swad to networks")`

And the use of '--bool_swad‘  is in POEM/domainbed/trainer.py  at 178 row.
```
    swad = None
    if args.bool_swad:
        if hparams["swad"]:
            swad_algorithm = swa_utils.AveragedModel(algorithm)
            swad_cls = getattr(swad_module, hparams["swad"])
            swad = swad_cls(evaluator, **hparams.swad_kwargs)
```

I think maybe '--bool_swad‘  is also a switch to swad.

Thanks!
